### ISSUE TITLE
Problem with  - CUDA_ACCELERATION=true, container exits

### ISSUE THREAD

**Issue by Deathproof76** [imagegenius/docker-immich#101]
Was working until yesterday, after a reboot this happened:

Docker-compose.yml

```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: immich
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DB_HOSTNAME=XXXXXX
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=XXXXXX
      - DISABLE_MACHINE_LEANRNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5438 #optional
      - REDIS_PORT=6579 #optional
      - REDIS_PASSWORD=XXXXXXXXX
      - CUDA_ACCELERATION=true #optional
    volumes:
      - /mnt/XXXXXX/immich/config:/config
      - /mnt/XXXXXXX/immich/photos:/photos
      - /mnt/XXXXXX/immich/machine-learning:/config/machine-learning #optional
    ports:
      - XXXXX
  redis2:
    image: redis
    ports:
      - XXXXX
    container_name: redis2
    restart: unless-stopped
    command: redis-server --requirepass XXXXXXXX

  postgres14:
    image: postgres:14
    ports:
      - XXXXXX
    container_name: postgres14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /mnt/XXXXX/immich/postgres:/var/lib/postgresql/data
```

The startup logs:
```
immich      | Setting up libpython3-dev:amd64 (3.11.2-1) ...
immich      | Setting up python3.11-dev (3.11.2-6ubuntu0.1) ...
immich      | Setting up python3-dev (3.11.2-1) ...
immich      | Processing triggers for libc-bin (2.37-0ubuntu2) ...
immich      | /etc/s6-overlay/s6-rc.d/init-config-cuda/run: line 20: /config/cuda-venv/bin/pip: cannot execute: required file not found
immich      | /etc/s6-overlay/s6-rc.d/init-config-cuda/run: line 22: /config/cuda-venv/bin/pip: cannot execute: required file not found
immich      | Reading package lists...
immich      | Building dependency tree...
immich      | Reading state information...
```

...........................

```
immich      | ERROR:    Application startup failed. Exiting.
immich      | INFO:     Started server process [1893]
immich      | INFO:     Waiting for application startup.
immich      | Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
immich      | The `max_size` parameter is deprecated and will be removed in v4.26. Please specify in `size['longest_edge'] instead`.
immich      | ERROR:    Traceback (most recent call last):
immich      |   File "/usr/lib/python3/dist-packages/starlette/routing.py", line 671, in lifespan
immich      |     async with self.lifespan_context(app):
immich      |   File "/usr/lib/python3/dist-packages/starlette/routing.py", line 566, in __aenter__
immich      |     await self._router.startup()
immich      |   File "/usr/lib/python3/dist-packages/starlette/routing.py", line 648, in startup
immich      |     await handler()
immich      |   File "/app/immich/machine-learning/src/main.py", line 47, in startup_event
immich      |     _get_model(object_model, "object-detection")
immich      |   File "/app/immich/machine-learning/src/main.py", line 152, in _get_model
immich      |     _model_cache[key] = pipeline(model=model, task=task, device=device_pipeline)
immich      |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich      |   File "/usr/local/lib/python3.11/dist-packages/transformers/pipelines/__init__.py", line 988, in pipeline
immich      |     return pipeline_class(model=model, framework=framework, task=task, **kwargs)
immich      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich      |   File "/usr/local/lib/python3.11/dist-packages/transformers/pipelines/object_detection.py", line 50, in __init__
immich      |     super().__init__(*args, **kwargs)
immich      |   File "/usr/local/lib/python3.11/dist-packages/transformers/pipelines/base.py", line 781, in __init__
immich      |     self.model.to(device)
immich      |   File "/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py", line 1878, in to
immich      |     return super().to(*args, **kwargs)
immich      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich      |   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1145, in to
immich      |     return self._apply(convert)
immich      |            ^^^^^^^^^^^^^^^^^^^^
immich      |   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 797, in _apply
immich      |     module._apply(fn)
immich      |   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 797, in _apply
immich      |     module._apply(fn)
immich      |   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 797, in _apply
immich      |     module._apply(fn)
immich      |   [Previous line repeated 1 more time]
immich      |   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 820, in _apply
immich      |     param_applied = fn(param)
immich      |                     ^^^^^^^^^
immich      |   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1143, in convert
immich      |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
immich      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich      |   File "/usr/local/lib/python3.11/dist-packages/torch/cuda/__init__.py", line 239, in _lazy_init
immich      |     raise AssertionError("Torch not compiled with CUDA enabled")
immich      | AssertionError: Torch not compiled with CUDA enabled
immich      | 

```

Works as expected with CUDA_ACCELERATION=false
