### ISSUE TITLE
Unable to reach the interface

### ISSUE THREAD

**Issue by edersong** [imagegenius/docker-immich#143]
I deployed the ghcr.io/imagegenius/immich:latest docker version of Immich and it was deployed successfully. No errors are being reported, but when I try to access it thru http://my-ip:8080/ it's not opening.
Tried also to configure it thru Nginx Proxy Manager but it still failing to open.
My current compose file is:

```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DB_HOSTNAME=immich_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - CUDA_ACCELERATION=false #optional
    volumes:
      - immich_conf:/config
      - /mnt/Media:/photos
      - immich_machine-learning:/config/machine-learning #optional
    ports:
      - 8080:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# Redis:
  redis:
    image: redis
    hostname: immich_redis
    container_name: immich_redis
# PostgreSQL 14:
  postgres14:
    image: postgres:14

    container_name: immich_db
    hostname: immich_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - immich_db:/var/lib/postgresql/data
volumes:
  immich_conf:
    name: immich_conf
  immich_machine-learning:
    name: immich_machine-learning
  immich_db:
    name: immich_db
No errors were found at the containers
```

Redis:

```
1:C 14 Jul 2023 07:48:00.668 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 14 Jul 2023 07:48:00.668 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 14 Jul 2023 07:48:00.668 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 14 Jul 2023 07:48:00.670 * monotonic clock: POSIX clock_gettime
1:M 14 Jul 2023 07:48:00.675 * Running mode=standalone, port=6379.
1:M 14 Jul 2023 07:48:00.675 # Server initialized
1:M 14 Jul 2023 07:48:00.676 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 14 Jul 2023 07:48:00.721 * Loading RDB produced by version 7.0.12
1:M 14 Jul 2023 07:48:00.721 * RDB age 11 seconds
1:M 14 Jul 2023 07:48:00.721 * RDB memory usage when created 0.87 Mb
1:M 14 Jul 2023 07:48:00.721 * Done loading RDB, keys loaded: 10, keys expired: 0.
1:M 14 Jul 2023 07:48:00.721 * DB loaded from disk: 0.042 seconds
1:M 14 Jul 2023 07:48:00.721 * Ready to accept connections
```
Database:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-07-14 07:48:02.908 UTC [1] LOG:  starting PostgreSQL 14.8 (Debian 14.8-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-07-14 07:48:02.911 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-07-14 07:48:02.912 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-07-14 07:48:02.927 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-07-14 07:48:03.058 UTC [27] LOG:  database system was shut down at 2023-07-14 07:47:49 UTC
2023-07-14 07:48:03.208 UTC [1] LOG:  database system is ready to accept connections
```
Server:

```
[migrations] started
[migrations] no migrations found
╔═══════════════════════════════╗
      __  _____ _____       __
     / / |_   _/ ____|     / /
    / /    | || |  __     / /
   / /     | || | |_ |   / /
  / /     _| || |__| |  / /
 /_/     |_____\_____| /_/
 Baseimage from linuxserver.io
╠═══════════════════════════════╣
 To support this applications developer(s) visit:
 Immich: https://immich.app/docs/overview/support-the-project
╠═══════════════════════════════╣
 User/Group ID:
 User UID: 1000
 User GID: 1000
╚═══════════════════════════════╝
```
Any idea what's going on?
