### ISSUE TITLE
Postgres Docker Compose example template

### ISSUE THREAD

**Issue by Hukuma1** [imagegenius/docker-immich#16]
Sorry, not sure how to do a PR, but for anyone installing this all-in-one Docker container via Docker Compose, here would be the current yml code for you. This is for people who do not run Postgres or Redis elsewhere:

```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=somelongrandomstring
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
    ports:
      - 8080:8080
    restart: unless-stopped
    
  postgres:
    image: postgres:14
    container_name: postgres14
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=immich
    volumes:
      - path_to_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
```

Btw I had to remap port `3001` which Immich uses to another port due to to Uptime-Kuma using the same one. Not sure if a variable to remap is needed, or if it's enough to just instruct people to do `3002:3001` under ports for Immich container.

Thank you for this! Can't wait for the docker-mod of Postgres to be added.

**Comment by hydazz** [comment]
I will add this into the readme, (trying to make it as less confusing as possible).

> Thank you for this! Can't wait for the docker-mod of Postgres to be added.

I have a semi complete docker-mod for postgres if you want to test it out,
https://github.com/imagegenius/docker-mods/tree/universal-postgres
this mod works on alpine and ubuntu, (`:noml` + `:latest` here)

```yaml
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=somelongrandomstring
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
    ports:
      - 8080:8080
    restart: unless-stopped
```
