### ISSUE TITLE
Immich now supports GPU Transcoding

### ISSUE THREAD

**Issue by travisboss** [imagegenius/docker-immich#189]
I see the options available in the GUI and I enabled `cuda_acceleration` and here is my compose file:

```yaml
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - DB_HOSTNAME=postgres14
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - DISABLE_MACHINE_LEARNING=false #optional
     #- IMMICH_MACHINE_LEARNING_URL=http://immich-cuda-node:3003
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - CUDA_ACCELERATION=true #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /pool/datavault/immich/config:/config
      - /pool/datavault/immich/photos:/photos
    ports:
      - 9089:8080
    restart: unless-stopped
    networks:
      - docker-services
    depends_on:
      - postgres14
    security_opt:
      - no-new-privileges=true
  ```

I have followed the jellyfin style of adding the nvidia runtime, this is how linuxserver recommends adding support.

```
[auto_aresample_0 @ 0x40ad41d0380] ch:1 chl:mono fmt:s16 r:44100Hz -> ch:1 chl:mono fmt:fltp r:44100Hz
[graph 0 input from stream 0:0 @ 0x40ad41e2d00] w:1920 h:1440 pixfmt:yuvj420p tb:1/600 fr:60000/1001 sar:0/1
    Metadata:
      creation_time   : 2021-05-03T15:36:41.000000Z
      handler_name    : Core Media Metadata
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[graph_1_in_0_1 @ 0x42ad41e5580] tb:1/44100 samplefmt:s16 samplerate:44100 chlayout:mono
[format_out_0_1 @ 0x42ad41e57c0] auto-inserting filter 'auto_aresample_0' between the filter 'Parsed_anull_0' and the filter 'format_out_0_1'
[auto_aresample_0 @ 0x42ad41e5880] ch:1 chl:mono fmt:s16 r:44100Hz -> ch:1 chl:mono fmt:fltp r:44100Hz
[graph 0 input from stream 0:0 @ 0x42ad41e30c0] w:1920 h:1440 pixfmt:yuvj420p tb:1/600 fr:30000/1001 sar:0/1
[auto_scale_0 @ 0x42ad41e6180] w:iw h:ih flags:'' interl:0
[transpose @ 0x42ad41e2e80] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'transpose'
[swscaler @ 0x42ae451a000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x42ad41e6180] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[transpose @ 0x42ad41e2e80] w:1920 h:1440 dir:1 -> w:1440 h:1920 rotation:clockwise vflip:0
[Parsed_scale_cuda_2 @ 0x42ad41e3a80] w:1440 h:1920 -> w:1080 h:1440
[swscaler @ 0x42ae451a000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x42ad41e6180] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[swscaler @ 0x42ae451a000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x42ad41e6180] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[swscaler @ 0x42ae451a000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x42ad41e6180] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[h264_nvenc @ 0x42ad41b7d80] Using input frames context (format cuda) with h264_nvenc encoder.
[h264_nvenc @ 0x42ad41b7d80] Cannot load libnvidia-encode.so.1
[h264_nvenc @ 0x42ad41b7d80] The minimum required Nvidia driver for nvenc is 520.56.06 or newer
[h264_nvenc @ 0x42ad41b7d80] Nvenc unloaded
[vost#0:0/h264_nvenc @ 0x42ad4d01680] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x42ad41b8980] Qavg: 109.819
[aac @ 0x42ad41b8980] 2 frames left in the queue on closing
[AVIOContext @ 0x42ad41193c0] Statistics: 0 bytes written, 0 seeks, 0 writeouts
Terminating demuxer thread 0
[AVIOContext @ 0x42ad41175c0] Statistics: 944871 bytes read, 16 seeks
Conversion failed!
```

Any thoughts or am I getting ahead of myself?
