### ISSUE TITLE
error: database "immich" does not exist 

### ISSUE THREAD

**Issue by itangqiao** [imagegenius/docker-immich#192]
<h3 dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(230, 237, 243); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The bug</h3>

2023/10/13 04:50:36 | stderr | at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
-- | -- | --
2023/10/13 04:50:36 | stderr | at Readable.push (node:internal/streams/readable:234:10)
2023/10/13 04:50:36 | stderr | at readableAddChunk (node:internal/streams/readable:297:9)
2023/10/13 04:50:36 | stderr | at addChunk (node:internal/streams/readable:324:12)
2023/10/13 04:50:36 | stderr | at Socket.emit (node:events:514:28)
2023/10/13 04:50:36 | stderr | at Socket. (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
2023/10/13 04:50:36 | stderr | at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
2023/10/13 04:50:36 | stderr | at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
2023/10/13 04:50:36 | stderr | at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
2023/10/13 04:50:36 | stderr | error: database "immich" does not exist
2023/10/13 04:50:36 | stderr | �[31m[Nest] 1828  - �[39m10/13/2023, 4:50:36 AM �[31m  ERROR�[39m �[38;5;3m[TypeOrmModule] �[39m�[31mUnable to connect to the database. Retrying (7)...�[39m
2023/10/13 04:50:33 | stderr | at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2023/10/13 04:50:33 | stderr | at Readable.push (node:internal/streams/readable:234:10)
2023/10/13 04:50:33 | stderr | at readableAddChunk (node:internal/streams/readable:297:9)
2023/10/13 04:50:33 | stderr | at addChunk (node:internal/streams/readable:324:12)
2023/10/13 04:50:33 | stderr | at Socket.emit (node:events:514:28)
2023/10/13 04:50:33 | stderr | at Socket. (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
2023/10/13 04:50:33 | stderr | at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
2023/10/13 04:50:33 | stderr | at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
2023/10/13 04:50:33 | stderr | at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
2023/10/13 04:50:33 | stderr | error: database "immich" does not exist

<img width="875" alt="image" src="https://github.com/imagegenius/docker-immich/assets/44393379/16d54528-acd0-4500-b34b-01c979b2588a">

```yml
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Asia/Shanghai
      - DB_HOSTNAME=192.168.3.3
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.3.3
      - DISABLE_MACHINE_LEANRNING=false
      - DISABLE_TYPESENSE=false
      - DB_PORT=15432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - CUDA_ACCELERATION=false
    volumes:
      - /volume1/docker/immich/config:/config
      - /volume1/docker/immich/photos:/photos
      - /volume1/docker/immich/machine:/config/machine-learning
    ports:
      - 18080:8080
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
  postgres14:
    image: postgres:14
    ports:
      - 15432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data

---
```
I was unable to start the immich container, so I executed the command "rm /volume1/@docker/containers/5c73117eb63f18d5f42a226378dfc83182320b4642654e9cdb25791b1a795367/log.db", but it still didn't work. Later, I tried deleting the relevant containers and recreating them, but it still doesn't work properly.
