### ISSUE TITLE
Errors with latest and noml images

### ISSUE THREAD

**Issue by vladosam** [imagegenius/docker-immich#20]
I am unable to run latest images "latest and noml-v1.45.0-ig27". Latest image that worked for me is "v1.43.1-ig34". Immich is on oracle vps. 
Latest docker compose:
```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Sarajevo
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxx
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres
    volumes:
      - /home/ubuntu/docker/immich/appdata:/config
      - /mnt/data/block/photos:/photos
    ports:
      - 8004:8080
    restart: unless-stopped
```
Error for latest:
```
immich    | node:internal/modules/cjs/loader:1249
immich    |   return process.dlopen(module, path.toNamespacedPath(filename));
immich    |                  ^
immich    | 
immich    | Error: /app/immich/machine-learning/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node: cannot open shared object file: No such file or directory
immich    |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
immich    |     at Module.load (node:internal/modules/cjs/loader:1043:32)
immich    |     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
immich    |     at Module.require (node:internal/modules/cjs/loader:1067:19)
immich    |     at require (node:internal/modules/cjs/helpers:103:18)
immich    |     at Object.<anonymous> (/app/immich/machine-learning/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
immich    |     at Module._compile (node:internal/modules/cjs/loader:1165:14)
immich    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
immich    |     at Module.load (node:internal/modules/cjs/loader:1043:32)
immich    |     at Function.Module._load (node:internal/modules/cjs/loader:878:12) {
immich    |   code: 'ERR_DLOPEN_FAILED'
immich    | }
```
Docker compose for latest noml:
```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:noml-v1.45.0-ig27
    container_name: immich
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Sarajevo
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxx
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres
    volumes:
      - /home/ubuntu/docker/immich/appdata:/config
      - /mnt/data/block/photos:/photos
    ports:
      - 8004:8080
    restart: unless-stopped
```
Error for noml:
```
immich    | node:internal/process/promises:288
immich    |             triggerUncaughtException(err, true /* fromPromise */);
immich    |             ^
immich    | 
immich    | Error: connect ECONNREFUSED 127.0.0.1:6379
immich    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
immich    | Emitted 'error' event on Commander instance at:
immich    |     at RedisSocket.<anonymous> (/app/immich/server/node_modules/@redis/client/dist/lib/client/index.js:360:14)
immich    |     at RedisSocket.emit (node:events:513:28)
immich    |     at RedisSocket._RedisSocket_connect (/app/immich/server/node_modules/@redis/client/dist/lib/client/socket.js:153:18)
immich    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich    |     at async Commander.connect (/app/immich/server/node_modules/@redis/client/dist/lib/client/index.js:173:9)
immich    |     at async Promise.all (index 0)
immich    |     at async RedisIoAdapter.connectToRedis (/app/immich/server/dist/apps/microservices/apps/immich/src/middlewares/redis-io.adapter.middleware.js:24:9)
immich    |     at async bootstrap (/app/immich/server/dist/apps/microservices/apps/microservices/src/main.js:16:5) {
immich    |   errno: -111,
immich    |   code: 'ECONNREFUSED',
immich    |   syscall: 'connect',
immich    |   address: '127.0.0.1',
immich    |   port: 6379
immich    | }
immich    | 
immich    | Node.js v18.12.1
```
Working docker compose v1.43.1-ig34:
```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:v1.43.1-ig34
    container_name: immich
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Sarajevo
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxx
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres
    volumes:
      - /home/ubuntu/docker/immich/appdata:/config
      - /mnt/data/block/photos:/photos
    ports:
      - 8004:8080
    restart: unless-stopped
```

**Comment by hydazz** [comment]
Is this running on an ARM instance?

**Comment by hydazz** [comment]
can you try `ghcr.io/imagegenius/igpipepr-immich:1.46.0-PR-22`

**Comment by hydazz** [comment]
this error should be fixed:
>immich    | node:internal/modules/cjs/loader:1249
immich    |   return process.dlopen(module, path.toNamespacedPath(filename));
immich    |                  ^
immich    | 
immich    | Error: /app/immich/machine-learning/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node: cannot open shared object file: No such file or directory
immich    |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
immich    |     at Module.load (node:internal/modules/cjs/loader:1043:32)
immich    |     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
immich    |     at Module.require (node:internal/modules/cjs/loader:1067:19)
immich    |     at require (node:internal/modules/cjs/helpers:103:18)
immich    |     at Object.<anonymous> (/app/immich/machine-learning/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
immich    |     at Module._compile (node:internal/modules/cjs/loader:1165:14)
immich    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
immich    |     at Module.load (node:internal/modules/cjs/loader:1043:32)
immich    |     at Function.Module._load (node:internal/modules/cjs/loader:878:12) {
immich    |   code: 'ERR_DLOPEN_FAILED'
immich    | }

this error on the noml branch 
>immich    | node:internal/process/promises:288
immich    |             triggerUncaughtException(err, true /* fromPromise */);
immich    |             ^
immich    | 
immich    | Error: connect ECONNREFUSED 127.0.0.1:6379
immich    |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
immich    | Emitted 'error' event on Commander instance at:
immich    |     at RedisSocket.<anonymous> (/app/immich/server/node_modules/@redis/client/dist/lib/client/index.js:360:14)
immich    |     at RedisSocket.emit (node:events:513:28)
immich    |     at RedisSocket._RedisSocket_connect (/app/immich/server/node_modules/@redis/client/dist/lib/client/socket.js:153:18)
immich    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich    |     at async Commander.connect (/app/immich/server/node_modules/@redis/client/dist/lib/client/index.js:173:9)
immich    |     at async Promise.all (index 0)
immich    |     at async RedisIoAdapter.connectToRedis (/app/immich/server/dist/apps/microservices/apps/immich/src/middlewares/redis-io.adapter.middleware.js:24:9)
immich    |     at async bootstrap (/app/immich/server/dist/apps/microservices/apps/microservices/src/main.js:16:5) {
immich    |   errno: -111,
immich    |   code: 'ECONNREFUSED',
immich    |   syscall: 'connect',
immich    |   address: '127.0.0.1',
immich    |   port: 6379
immich    | }
immich    | 
immich    | Node.js v18.12.1

shouldn't really be happening, whats the full output of docker logs?

**Comment by vladosam** [comment]
Yes, it ARM instance. With "1.46.0-PR-22" everything works and there are no errors in log :tada:.  Only warning "W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 33177600 exceeds 10% of free system memory."

**Comment by vladosam** [comment]
Is there noml version that i can test?

**Comment by hydazz** [comment]
can you run the noml branch with this docker-compose:

```yaml
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:noml
    container_name: immich
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Sarajevo
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - S6_VERBOSITY=2
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=<changeme>
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres
    volumes:
      - /home/ubuntu/docker/immich/appdata:/config
      - /mnt/data/block/photos:/photos
    ports:
      - 8004:8080
    restart: unless-stopped
```

paste back the enture output of the logs from `docker logs`
