### ISSUE TITLE
HW transcoding not working for Alpine (-noml) and Synology Intel 

### ISSUE THREAD

**Issue by dankcushions** [imagegenius/docker-immich#207]
Hi, Getting this sort of thing in the logs:

```
[Nest] 1167  - 11/12/2023, 6:34:50 PM     LOG [MediaService] Start encoding video 13b0f1ac-284d-4c41-80b4-1d202cc33f13 {"inputOptions":["-init_hw_device qsv=hw","-filter_hw_device hw"],"outputOptions":["-c:v h264_qsv","-c:a aac","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-bf 7","-refs 5","-g 256","-v verbose","-vf format=nv12,hwupload=extra_hw_frames=64,scale_qsv=720:-1","-preset 7","-global_quality 23"],"twoPass":false}
[Nest] 1167  - 11/12/2023, 6:34:50 PM   ERROR [MediaRepository] ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.1 (Alpine 13.2.1_git20231014) 20231014
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-lv2 --enable-openssl --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
[AVHWDeviceContext @ 0x7fd7a6624e40] Cannot open DRM render node for device 0.
[AVHWDeviceContext @ 0x7fd7a6624e40] Cannot open a VA display from DRM device (null).
Device creation failed: -542398533.
Failed to set value 'qsv=hw' for option 'init_hw_device': Generic error in an external library
Error parsing global options: Generic error in an external library

[Nest] 1167  - 11/12/2023, 6:34:50 PM   ERROR [MediaService] Error: ffmpeg exited with code 1: Device creation failed: -542398533.
Failed to set value 'qsv=hw' for option 'init_hw_device': Generic error in an external library
Error parsing global options: Generic error in an external library

[Nest] 1167  - 11/12/2023, 6:34:50 PM   ERROR [MediaService] Error occurred during transcoding. Retrying with QSV acceleration disabled.
```

This is with a [Synology 423+ NAS](https://www.synology.com/en-global/products/DS423+#specs) which has Intel J4124, which has quicksync.

Here's my docker compose:

```
  immich:
    image: ghcr.io/imagegenius/immich:noml
    container_name: immich
    privileged: true #needed for hw transcoding on synology (?)
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=postgres
      - REDIS_HOSTNAME=localhost
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres
    volumes:
      - ${CONFIG}/immich:/config
      - ${MEDIA}/photos:/photos
      - /volume1/photos:/import:ro #optional, delete after!
    ports:
      - 8080:8080
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    restart: unless-stopped
```

(I am not sure if `privileged: true` is needed, but is used in my Plex service, where hardware transcoding via ` - /dev/dri:/dev/dri` works fine)

I have not tried the regular image, or indeed the immich vanilla docker compose, but I was under the impression that hw transcoding might work in alpine as per https://github.com/imagegenius/docker-immich/pull/148#issuecomment-1655386160

These errors look like a driver type issue, so I wonder if maybe the above PR or https://github.com/imagegenius/docker-immich/pull/168 are not available/possible in the noml image?

**Comment by martabal** [comment]
Right, I didn't test if the noml version is compatible with hardware transoding and I wouldn't be surprised if it is not. As for #168, it addresses a permission issue. If you'd like to test it, follow these steps: create a new `fix.sh` file on your machine within a new `custom-cont-init.d` folder. Copy the content of this file https://github.com/imagegenius/docker-immich/blob/main/root/etc/s6-overlay/s6-rc.d/init-video-immich/run into `fix.sh`, and then make `fix.sh` executable using `chmod +x fix.sh` command. ([Here](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) the official guide about custom scripts) 

Then add the new volume to your immich container
```yaml
    volumes:
      - ${CONFIG}/immich:/config
      - ${MEDIA}/photos:/photos
      - ${CONFIG}/custom-cont-init.d:/custom-cont-init.d:ro
  ```

If this does not work, this is definetly an alpine issue

**Comment by dankcushions** [comment]
Thanks. Looks like something different is happening, at least!

```
[Nest] 1214  - 11/13/2023, 6:43:40 PM     LOG [MediaService] Start encoding video e67d1414-8e7f-48b5-a99c-0337663e22ae {"inputOptions":["-init_hw_device qsv=hw","-filter_hw_device hw"],"outputOptions":["-c:v h264_qsv","-c:a aac","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-bf 7","-refs 5","-g 256","-v verbose","-vf format=nv12,hwupload=extra_hw_frames=64,scale_qsv=720:-1","-preset 7","-global_quality 23"],"twoPass":false}
[Nest] 1214  - 11/13/2023, 6:43:40 PM   ERROR [MediaRepository] ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.1 (Alpine 13.2.1_git20231014) 20231014
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-lv2 --enable-openssl --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
[AVHWDeviceContext @ 0x7f547b06be40] Trying to use DRM render node for device 0, with matching kernel driver (i915).
[AVHWDeviceContext @ 0x7f547b06be40] libva: VA-API version 1.20.0
[AVHWDeviceContext @ 0x7f547b06be40] libva: User requested driver 'iHD'
[AVHWDeviceContext @ 0x7f547b06be40] libva: Trying to open /usr/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x7f547b06be40] libva: va_openDriver() returns -1
[AVHWDeviceContext @ 0x7f547b06be40] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value 'qsv=hw' for option 'init_hw_device': I/O error
Error parsing global options: I/O error

[Nest] 1214  - 11/13/2023, 6:43:40 PM   ERROR [MediaService] Error: ffmpeg exited with code 1: Device creation failed: -5.
Failed to set value 'qsv=hw' for option 'init_hw_device': I/O error
Error parsing global options: I/O error

[Nest] 1214  - 11/13/2023, 6:43:40 PM   ERROR [MediaService] Error occurred during transcoding. Retrying with QSV acceleration disabled.
[Nest] 1214  - 11/13/2023, 6:43:41 PM     LOG [MediaService] Encoding success e67d1414-8e7f-48b5-a99c-0337663e22ae
```

Looks like it fails hw transcoding with a device creation / IO error, and then falls back to software and succeeds. i'm a bit of a linux dumbass so i'm hoping these permissions are right:

```
drwxrwxrwx+ 1 docker users 12 Nov 13 18:26 custom-cont-init.d
chris@synology:~$ ls -l custom-cont-init.d/fix.sh 
-rwxrwxrwx+ 1 docker users 1687 Nov 13 18:26 custom-cont-init.d/fix.sh
```

(the docker user is what is assigned to the PGID/PUID of the immich container)

**Comment by martabal** [comment]
Can you pull the image again. `noml` has been rebased to ubuntu. The image is a bit bigger and has typesense but no machine-learning. HW transcoding should work fine.

**Comment by dankcushions** [comment]
thanks! I have tried after a pull and get a lot of this error now :

```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
```

I am using the docker-compose in my first post. So it's using `universal-redis` mod as per the readme suggestion
```
      - REDIS_HOSTNAME=localhost
      - DOCKER_MODS=imagegenius/mods:universal-redis
 ```

It seemed to work before, at least!

**Comment by martabal** [comment]
Can you try to delete the redis folder in `/config` ?

**Comment by dankcushions** [comment]
Tried that, and still getting similar errors, but there's a few strange ones earlier that may be releated:

```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-14
chown: invalid user: ‘postgres:postgres’
PostgreSQL Database Already Initialised
[custom-init] No custom files found, skipping...
s6-envuidgid: fatal: unknown user: postgres
s6-rc: warning: unable to start service svc-mod-universal-postgres: command exited 1
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
s6-applyuidgid: fatal: unable to exec redis-server: No such file or directory
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [NestFactory] Starting Nest application...
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +71ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +2ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +9ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
[Nest] 434  - 11/14/2023, 11:56:44 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 434  - 11/14/2023, 11:56:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
```

**Comment by martabal** [comment]
Oh damn are you using the postgres docker mod ? I don't understand why you have such errors with redis. @hydazz any ideas ?

**Comment by hydazz** [comment]
the postgres docker mod continued to work on alpine, as their package support is more legacy, but its now based on debian and there is no postgres 14, I presume that its trying to install PG14, failing and skipping installing redis

**Comment by hydazz** [comment]
redis is not installed, as postgres fails to install

**Comment by dankcushions** [comment]
Sorry for the delay. I have added postgres to my -noml compose, rather than use the docker mod. i am getting a loop of:
```
[Nest] 360  - 11/28/2023, 11:09:12 PM     LOG [NestFactory] Starting Nest application...
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +67ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +2ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +10ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 360  - 11/28/2023, 11:09:13 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 360  - 11/28/2023, 11:09:13 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:16 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:19 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:22 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:28 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:31 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:34 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:37 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
[Nest] 360  - 11/28/2023, 11:09:37 PM   ERROR [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```
Note I am still using postgres 14, as using postgres 15 as per the latest readme gives me a compatibility error with my previously built postgres 14 database. i could just delete this but i presume that will cause problems with my current immich installation(?).

also note that I'm not using external db port 5432 as synology OS already uses that for something, so I have forwarded from 6543 (I think). 

```
  immich:
    image: ghcr.io/imagegenius/immich:noml
    container_name: immich
    privileged: true #needed for hw transcoding on synology (?)
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - DB_PORT=5432
      - REDIS_HOSTNAME=localhost
      - DOCKER_MODS=imagegenius/mods:universal-redis
    volumes:
      - ${CONFIG}/immich:/config
      - ${MEDIA}/photos:/photos
      - /volume1/photos:/import:ro #optional, delete after!
#      - ${DATA}/chris/custom-cont-init.d:/custom-cont-init.d:ro
    ports:
      - 8080:8080
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    depends_on:
      - postgres14
    restart: unless-stopped

  postgres14:
    image: postgres:14
    container_name: immich_db
    ports:
      - 6543:5432 # 5432 is taken on host, so forward from 6543
    user: "${PUID}:${PGID}"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - ${CONFIG}/immich/postgres:/var/lib/postgresql/data
    restart: unless-stopped
```
