### ISSUE TITLE
Help with iGPU transcoding

### ISSUE THREAD

**Issue by dsfsdbvxc** [imagegenius/docker-immich#226]
Looking for a bit of help with getting intel quicksync transcoding set up with this container and Unraid.

I've passed the iGPU through using --device=/dev/dri/ as an extra parameter. The docker compose equivilant to     

devices:
       - /dev/dri:/dev/dri

Then enabled hardware accelleration in Immich, via settings > hardware acceleration > ACCELERATION API > Select Quicksync

Looking through the [immich documentation](https://immich.app/docs/features/hardware-transcoding) the steps are where I get stuck as not how to do this in Unraid: 

1) If you do not already have it, download the latest [hwaccel.yml](https://github.com/immich-app/immich/releases/latest/download/hwaccel.yml) file and ensure it's in the same folder as the docker-compose.yml.
2) Uncomment the lines that apply to your system and desired usage.
3) In the docker-compose.yml under immich-microservices, uncomment the lines relating to the hwaccel.yml file.
4) Redeploy the immich-microservices container with these updated settings.

Any help appreciated

**Comment by martabal** [comment]
With what you described, it's supposed to work. Use this guide only if you deployed immich with the official containers which is not your case

**Comment by dsfsdbvxc** [comment]
Thanks for the reply.

Humm, ok, looking at the GPU load it doesn't look like its being used (intel 12500), can I just check expected behaviour when transcoding. Appreciate its an experemental feature.

I'm using an external library, started a scan and transcoding using 'only video not in the desired format'. Would this be expected to use the GPU or is it when a video's played back and transcoded on the fly?

**Comment by martabal** [comment]
If your videos use a compatible codec, I don't they need to be transcoded

**Comment by Hely0n** [comment]
Same here. I added devices: /dev/dri too and enabled it in the immich settings. Then I set "transcode all videos not in desired format" (I had transcoding disabled until now) and started the Transcoding Queue. It fills up and is starts to work, but iGPU shows no load, while 2 CPU cores are on 100%, thus it's not transcoding via iGPU.

**Comment by Hely0n** [comment]
This is my Docker-compose:
```

version: "3.8"
name: immich
services:
  immich:
    depends_on:
      - db
      - redis
    image: ghcr.io/imagegenius/immich:latest
    container_name: Immich-App
    environment:
      - TZ=Europe/Berlin
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=...
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - CUDA_ACCELERATION=false #optional
    volumes:
      ...
    ports:
      - 3000:8080
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    restart: always

  # This container requires an external application to be run separately to be run separately.
  # Redis:
  redis:
    image: redis
    container_name: Immich-Redis
    restart: always
    volumes:
      - "/mnt/user/appdata/Immich/redis:/data"
  
  # PostgreSQL 14:
  db:
    image: postgres:14
    container_name: Immich-DB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ...
      POSTGRES_DB: immich
    volumes:
      - "/mnt/user/appdata/Immich/db:/var/lib/postgresql/data"
      
volumes:
   unused_data:
```
