### ISSUE TITLE
Unable to import external libraries

### ISSUE THREAD

**Issue by bloodyburger** [imagegenius/docker-immich#253]
Installed docker and started immich via docker compose. Mounted external library which is mounted via rclone in host machine. I can see the files inside immich docker at ```/import```  but when I add them in UI doesn't recognise any files.

```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/hh10tb/od1:/import
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
 #     - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/hh10tb/od1:/import
    env_file:
      - .env
    depends_on:
      - redis
 #     - database
      - typesense
    restart: always
```
I have added the path ```/import``` in admin settings and using the same path in profile page as well. What am I missing?

**Comment by martabal** [comment]
Make sure you have the correct permissions

**Comment by bloodyburger** [comment]
I am able to see the files within immich docker, does that not tell the permissions are ok? or do I have to check anything else?

**Comment by martabal** [comment]
Nope, it does not mean your permissions are ok. Set the same permissions for `/import`  as the files in `/photos`

**Comment by bloodyburger** [comment]
I do not see any ```/photos```

**Comment by bloodyburger** [comment]
you may be right, I used the docker-compose from official site, let me try replacing with this one.

**Comment by bloodyburger** [comment]
I used the below docker-compose but why am I seeing no migrations found. 
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding imagegenius/mods:universal-redis to container
[mod-init] Downloading imagegenius/mods:universal-redis from registry-1.docker.io
[mod-init] Installing imagegenius/mods:universal-redis
[mod-init] imagegenius/mods:universal-redis applied to container
[migrations] started
[migrations] no migrations found

╔═══════════════════════════════╗
       __  _____ _____       __
      / / |_   _/ ____|     / /
     / /    | || |  __     / /
    / /     | || | |_ |   / /
   / /     _| || |__| |  / /
  /_/     |_____\_____| /_/

  Baseimage from linuxserver.io
╠═══════════════════════════════╣
  To support this applications developer(s) visit:
  Immich: https://immich.app/docs/overview/support-the-project
╠═══════════════════════════════╣
  User/Group ID:
  User UID: 1000
  User GID: 1000
╚═══════════════════════════════╝
```
```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=my_postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345678
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_WORKERS=4 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis
    volumes:
      - ./config:/config
      - ./photos:/photos
      - ./ml:/config/machine-learning #optional
      - /mnt/hh10tb:/import:ro #optional
    ports:
      - 8080:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis

networks:
  default:
    external:
       name: charkoal

```
