### ISSUE TITLE
DB_HOSTNAME change 

### ISSUE THREAD

**Issue by Greedwolf** [imagegenius/docker-immich#267]
I installed it through Docker Compose, but when I restart Docker, the IP addresses obtained by immich, Redis, and postgres sometimes change, causing it to not start. How to modify Docker Compose to automatically adapt to this IP change for immich

**Comment by hydazz** [comment]
you can set the ip to the hostname of the container, the hostname should be the `container_name`, eg:

```yaml
services:
  immich:
    image: ghcr.io/imagegenius/igpipepr-immich:1.91.4-PR-266
    container_name: immich
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Australia/Melbourne'
      DB_HOSTNAME: 'postgres14' # <= container name
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_DATABASE_NAME: 'immich'
      REDIS_HOSTNAME: 'redis'
      DB_PORT: '5432'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: ''
      MACHINE_LEARNING_WORKERS: '1'
      MACHINE_LEARNING_WORKER_TIMEOUT: '120'
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - postgres14
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'
    container_name: redis
    restart: unless-stopped

  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    ports:
      - '5432:5432'
    container_name: postgres14 # <= set here
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'immich'
    restart: unless-stopped
```
