### ISSUE TITLE
BUG - Container doesn't have permission to write to the /photos dir (but it does!)

### ISSUE THREAD

**Issue by jamess60** [imagegenius/docker-immich#292]
Hi

I am no longer able to upload photos to my immich instance and the logs (exert below) show that the container cannot write to /photos.

/photos is volume mapped to a directory that sits on an SMB share. If I drop into the shell of the container, It is able to read and write to /photos no issue, and I see those changes reflected outside of the container too. 

Am I missing something? 

Docker compose:

```
    immich:
        container_name: immich
        image: ghcr.io/imagegenius/immich:latest
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - DB_HOSTNAME=immich-db
            - DB_USERNAME=CENCORED
            - DB_PASSWORD=CENSORED
            - DB_DATABASE_NAME=immich
            - REDIS_HOSTNAME=immich-redis
            - DISABLE_MACHINE_LEARNING=false
            - DISABLE_TYPESENSE=false
            - DB_PORT=5032
            - REDIS_PORT=5031
            - MACHINE_LEARNING_WORKERS=4
            - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
        volumes:
            - /containers/v-cont-01/data/immich/config:/config
            - /mnt/v-fs-01/NAS1A/Large-Container-Data/immich/photos:/photos
            - /containers/v-cont-01/data/immich/ml:/config/machine-learning #optional
            - /containers/v-cont-01/data/immich/import:/import:ro #optional
        ports:
            - 5030:8080
        restart: always
        devices:
            - /dev/dri:/dev/dri
    immich-redis:
        container_name: immich-redis
        image: redis:latest
        ports:
            - 5031:5031
        command: redis-server --port 5031
        restart: always
    immich-db:
        container_name: immich-db
        # image: postgres:14
        image: tensorchord/pgvecto-rs:pg14-v0.1.11
        ports:
            - 5032:5032
        environment:
            POSTGRES_USER: CENSORED
            POSTGRES_PASSWORD: CENSORED
            POSTGRES_DB: immich
            PGPORT: 5032
        volumes:
            - /containers/v-cont-01/data/immich/db:/var/lib/postgresql/data
        restart: always
```

Logs:
```
[Nest] 347  - 01/29/2024, 12:40:41 PM   ERROR [Error: EACCES: permission denied, mkdir '/photos/upload/f399754f-069b-4859-a8f1-f91dc678b653/14/52'

    at mkdirSync (node:fs:1380:26)

    at FilesystemProvider.mkdirSync (/app/immich/server/dist/infra/repositories/filesystem.provider.js:114:32)

    at AssetService.getUploadFolder (/app/immich/server/dist/domain/asset/asset.service.js:121:32)

    at /app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:122:52

    at callbackify (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:62:37)

    at FileUploadInterceptor.destination (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:122:16)

    at DiskStorage._handleFile (/app/immich/server/node_modules/multer/storage/disk.js:31:8)

    at FileUploadInterceptor.handleFile (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:132:29)

    at /app/immich/server/node_modules/multer/lib/make-middleware.js:137:17

    at callbackify (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:62:16)] Failed to upload file

[Nest] 347  - 01/29/2024, 12:40:41 PM   ERROR [Error: EACCES: permission denied, mkdir '/photos/upload/f399754f-069b-4859-a8f1-f91dc678b653/14/52'

    at mkdirSync (node:fs:1380:26)

    at FilesystemProvider.mkdirSync (/app/immich/server/dist/infra/repositories/filesystem.provider.js:114:32)

    at AssetService.getUploadFolder (/app/immich/server/dist/domain/asset/asset.service.js:121:32)

    at /app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:122:52

    at callbackify (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:62:37)

    at FileUploadInterceptor.destination (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:122:16)

    at DiskStorage._handleFile (/app/immich/server/node_modules/multer/storage/disk.js:31:8)

    at FileUploadInterceptor.handleFile (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:132:29)

    at /app/immich/server/node_modules/multer/lib/make-middleware.js:137:17

    at callbackify (/app/immich/server/dist/immich/interceptors/file-upload.interceptor.js:62:16)] Error: EACCES: permission denied, mkdir '/photos/upload/f399754f-069b-4859-a8f1-f91dc678b653/14/52'
```
