### ISSUE TITLE
the search bar doesn't work

### ISSUE THREAD

**Issue by Shihta** [imagegenius/docker-immich#297]
it shows

![截圖 2024-02-14 晚上8 50 39](https://github.com/imagegenius/docker-immich/assets/5186176/fa0395c9-22c0-4036-8dd7-3a9a0315691f)

```
Smart search is not enabled (400 - Bad Request)

Stacktrace
AxiosError: Request failed with status code 400
    at nn (http://192.168.28.90:8081/_app/immutable/chunks/api.hDXpMC_1.js:3:1042)
    at XMLHttpRequest.b (http://192.168.28.90:8081/_app/immutable/chunks/api.hDXpMC_1.js:3:4227)
    at ze.request (http://192.168.28.90:8081/_app/immutable/chunks/api.hDXpMC_1.js:5:3105)
    at async He (http://192.168.28.90:8081/_app/immutable/nodes/23.BZLJ7Gde.js:1:1764)
    at async be (http://192.168.28.90:8081/_app/immutable/chunks/entry.YqhOxQ9H.js:1:12871)
```

**Comment by martabal** [comment]
What version are you using ? `noml` ?

**Comment by Shihta** [comment]
> What version are you using ? `noml` ?

ghcr.io/imagegenius/immich:arm64v8-1.94.1-alpine

my docker-compose.yml is shown as the follows:
```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:arm64v8-1.94.1-alpine
    environment:
      - TZ=Asia/Taipei
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
    volumes:
      - /mnt/md0/immich-data2/immich/config:/config
      - /mnt/md0/immich-data2/immich/photos:/photos
    ports:
      - 8081:8080
    restart: always
# This container requires an external application to be run separately to be run separately.
# Redis:
  redis:
    image: redis:7.2.4-alpine
    restart: always
# PostgreSQL:
  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.1.11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /mnt/md0/immich-data2/postgres:/var/lib/postgresql/data
```
