### ISSUE TITLE
Unraid - Cant set a container path for /photos/thumbs

### ISSUE THREAD

**Issue by Zac-L** [imagegenius/docker-immich#338]
Would it be possible to add in a volume path for the thumbnails? Unless Im doing something wrong I cant seem to redirect the thumbs folder to anywhere other than where /photos lives. 

Thank you!

**Comment by martabal** [comment]
Absolutely, you can map your docker volumes as you wish

**Comment by hydazz** [comment]
to avoid mounting a mount in a mount, something like this would be desirable:

```yaml
services:
  immich:
    image: ghcr.io/imagegenius/immich:alpine
    container_name: immich
    env_file: stack.env
    volumes:
      - /mnt/appdata/immich:/config
      - /mnt/nfs/Picard/Media/Immich/encoded-video:/photos/encoded-video
      - /mnt/nfs/Picard/Media/Immich/library:/photos/library
      - /mnt/nfs/Picard/Media/Immich/thumbs:/photos/thumbs
      - /mnt/nfs/Picard/Media/Immich/upload:/photos/upload
    networks:
```
rather than:
```yaml
services:
  immich:
    image: ghcr.io/imagegenius/immich:alpine
    container_name: immich
    env_file: stack.env
    volumes:
      - /mnt/appdata/immich:/config
      - /mnt/nfs/Picard/Media/Immich:/photos
      - /mnt/nfs/Picard/Media/Immich/thumbs:/photos/thumbs # thumbs is being mounted into a mount, not good!
    networks:
```
obviously change `/mnt/nfs/Picard/Media/Immich/` to the root of your immich media, or elsewhere. you'll need to copy the contents of `thumbs` to the new location, or regenerate thumbnails
