### ISSUE TITLE
Immich and SWAG

### ISSUE THREAD

**Issue by HarvsG** [imagegenius/docker-immich#339]
I have runn immich using the following docker-compose

```yaml
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=postgres14
      - DB_USERNAME=postgres
      - DB_PASSWORD=asdkfakshdli32i342bf
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      #- MACHINE_LEARNING_GPU_ACCELERATION=1 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /home/pi/docker-files/immich/config:/config
      - /media/photos:/photos
      - /home/pi/docker-files/immich/import:/import:ro #optional
    ports:
      - 8081:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdkfakshdli32i342bf
      POSTGRES_DB: immich
    volumes:
      - /home/pi/docker-files/immich/postgres14:/var/lib/postgresql/data
```
I can access it successfully at `192.168.0.X:8081` however when I try and access it via SWAG (nginx) I get this page
![image](https://github.com/imagegenius/docker-immich/assets/11440490/c6e6be93-6c3f-4ccb-b9a3-5374a21f5f57)

```conf
# Immich Photos
server {
       listen 443 ssl http2;
       listen [::]:443 ssl http2;

       server_name immich.* photos.*;

       include /config/nginx/ssl.conf;

       client_max_body_size 0;

       satisfy any;
       include /config/nginx/internal.conf;
       include /config/nginx/vpn.conf;
       include /config/nginx/cloudflareIPs.conf;
       deny  all;
       location / {
               include /config/nginx/proxy.conf;
               resolver 127.0.0.11 valid=30s ipv6=off;
               #set $upstream_app immich;
               #set $upstream_port 8080;
               #set $upstream_proto http;
               #proxy_pass $upstream_proto://$upstream_app:$upstream_port;
       }
}
```
If I enter the console of swag and do `ping immich` and `curl immich:8080` I get successful pings and webpages respectively

Similarly if I ssh into immich and do `ping swag` it succeeds (after installing ping)
