### ISSUE TITLE
Database error on initial run

### ISSUE THREAD

**Issue by Medic97** [imagegenius/docker-immich#34]
I am trying to set this up use the docker mods command to have it all in one container. I am using docker on my QNAP Nas after creating the container it pulls the images and sets itself up but then gives a database error. Appreciate any help.

Here is my docker setup and I have attached my logs. 

```
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1004
      - PGID=100
      - TZ=America/New_York
      - DB_HOSTNAME=localhost
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - JWT_SECRET=somelongrandomstring
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis|imagegenius/mods:universal-postgres #set Docker mods for both Redis and PostgreSQL
    volumes:
      - /share/CACHEDEV1_DATA/Container/Docker Data/Immich:/config
      - /share/CACHEDEV3_DATA/NAS Pics:/photos
    ports:
      - 8080:8080
    network_mode: host #set network to bridge mode 
    restart: unless-stopped
```
```
2023-03-19 12:56:36.172 EDT [2026] FATAL:  database "immich" does not exist
[Nest] 1922  - 03/19/2023, 12:56:36 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/app/immich/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/immich/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/immich/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/immich/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/usr/local/lib/python3.10/dist-packages/transformers/models/yolos/image_processing_yolos.py:710: FutureWarning: The `max_size` parameter is deprecated and will be removed in v4.26. Please specify in `size['longest_edge'] instead`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_hip.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
```
