### ISSUE TITLE
can't run after installation

### ISSUE THREAD

**Issue by MuMu360121** [imagegenius/docker-immich#347]
Device: Qnap 466C
Docker compose:
```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DB_HOSTNAME=192.168.50.26
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.50.26
      - DB_PORT=15432 #optional
      - REDIS_PORT=16379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= cuda #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /share/CACHEDEV2_DATA/Container/immich/config:/config
      - /share/CACHEDEV1_DATA/Public/Photo:/photos
      - /share/CACHEDEV2_DATA/Container/immich/machine:/config/machine-learning #optional
      #- /share/CACHEDEV1_DATA/Public/docker/immich/imports:/import:ro #optional
    ports:
      - 18080:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - 16379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 15432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /share/CACHEDEV2_DATA/Container/immich/data:/var/lib/postgresql/data
```
log:
[_immich_logs.txt](https://github.com/imagegenius/docker-immich/files/15070296/_immich_logs.txt)
