### ISSUE TITLE
anyway to migrate from docker-immich to docker-compose?

### ISSUE THREAD

**Issue by wjfu99** [imagegenius/docker-immich#354]
Recently, I try to migrate from docker-immich to docker-compose, I map the /photos folder in docker-immich to /usr/src/app/upload/ in docker-compose version. But i found all the photos are unlinked and become into untracked files:
<img width="904" alt="image" src="https://github.com/imagegenius/docker-immich/assets/57850011/113022d1-a1d1-4962-8268-cde879ef21e9">
<img width="886" alt="image" src="https://github.com/imagegenius/docker-immich/assets/57850011/cbe632f3-63f4-4204-8d14-eb1d0e2d9288">

I guess in docker-immich's database, the uploading folder point to /photos, but in docker-compose's database, the uploading folder point to /usr/src/app/upload.
But i have no idea to slove this, i notice there is a issue about migrating from docker-compose to docker-immich #12 , i'm wonder if possible to migrate from docker-immich to docker-compose version?

**Comment by martabal** [comment]
You just need to add `- ${UPLOAD_LOCATION}:/photos` to your docker-compose.yml

**Comment by wjfu99** [comment]
@martabal Hi, thanks for your quick reply. If I understand correctly, I should add `- ${UPLOAD_LOCATION}:/photos` under `- ${UPLOAD_LOCATION}:/usr/src/app/upload` to my docker-compose.yml for `immich-server` and `immich-micorservice`, right? (If i just replace `-${UPLOAD_LOCATION}:/usr/src/app/upload` with `- ${UPLOAD_LOCATION}:/photos`, the newly added photos cannot be linked rightly, since them will still be added to the path `/usr/src/app/upload`).

After do that, the immich seems works well, but the issue raised in repair page let me a little annoy, the photos in `/photos` are marked as offline, the photos in `/usr/src/app/upload` are marked as untracked:
<img width="904" alt="image" src="https://github.com/imagegenius/docker-immich/assets/57850011/bb30d5bc-d187-4b9c-aa6d-fad2360ce4f3">
<img width="917" alt="image" src="https://github.com/imagegenius/docker-immich/assets/57850011/4ae463be-d676-45ac-a55d-b403342d51fc">

**Comment by wjfu99** [comment]
And I'm concerned that this migration will pollute the database, since the older photos will be recorded with path `/photos`, and newer photos will be recorded with `/usr/src/app/upload`. Should I just ignore these warning, or consider elegant migration scheme?
Or just keep using docker-immich, for me two main concerns are:
1. The computational consumption may be relatively higher?
2. docker-immich may stop update one day.

**Comment by martabal** [comment]
Have you already uploaded assets with the docker-compose.yml ?

**Comment by wjfu99** [comment]
sorry I have a little confusion, what the upload do you mean? I have mount the /photos folder (copied from my previous device and all assets are included here) to docker-compose immich, is this the upload you refer? 




发件人："martin" ***@***.***>
发送日期：2024-05-04 15:12:42
收件人："imagegenius/docker-immich" ***@***.***>
抄送人：
主 题：Re: [imagegenius/docker-immich] anyway to migrate from docker-immich to docker-compose? (Issue #354)


Have you already uploaded assets with the docker-compose.yml ?

**Comment by martabal** [comment]
Sorry, what I mean is have you uploaded assets after migrating from the AIO docker image to the official docker images ?

**Comment by wjfu99** [comment]
yes, i had tried to upload, the newly uploaded photos (here i mean i upload new photos, not the photos migrated from the old device) seems be treated well, it can be generated thumbnails, and can be previewed or downloaded. im just concern pollute the database. 
if you mean upload the assets from the old device, i haven't do that, i just mount the / photos folder from the old device for the newer one.

**Comment by martabal** [comment]
Weird, just adding `- ${UPLOAD_LOCATION}:/photos` should work fine. Are you sure you didn't have these errors even before the migration ?

**Comment by wjfu99** [comment]
I'm pretty sure the offline path and untracked file errors not exist before migration, but the offline path can still be previewed and downloaded. I refer my docker-compose.yml file as following:

```
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/photos
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
 ...
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardwa>
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcod>
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/photos
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
 ```
