### ISSUE TITLE
Immich doesn't start

### ISSUE THREAD

**Issue by denkyem** [imagegenius/docker-immich#394]
On latest version v1.107.2-ig299, Immich doesn't start, just stays like the in the screenshot

<img width="778" alt="image" src="https://github.com/imagegenius/docker-immich/assets/5843540/19252186-3a1c-4ba6-8aa9-9a56072ffd78">

**Comment by Hely0n** [comment]
I tought the same, but just waited a little longer and it worked

**Comment by martabal** [comment]
> I tought the same, but just waited a little longer and it worked

When the container starts, it checks if the folder mounted `/photos` has the correct permissions. If not, it tries to change it. This may take more or less time depending on the size of your library

**Comment by denkyem** [comment]
> I tought the same, but just waited a little longer and it worked

Well, that seams about right. After a really long time, it starts

**Comment by martabal** [comment]
> > I tought the same, but just waited a little longer and it worked
> 
> Well, that seams about right. After a really long time, it starts
> 
> Thanks

Can you open a new issue if you encounter this problem again, please? This shouldn't happen every time

**Comment by martabal** [comment]
Are you you guys using GPU acceleration with cuda?

**Comment by Janczykkkko** [comment]
I have the same issue, but interestingly it used to be waaaaay faster (1-2 mins) now its been going for an hour (drives io is heavily used so I assume its trying to change perms - BTW can this be disabled?. Going from v1.107.1-ig297 to v1.107.2-ig302.

**Comment by martabal** [comment]
Did you remove the `cuda` folder in `/config/machine-learning` ?

**Comment by Janczykkkko** [comment]
not using cuda, just the standard image ghcr.io/imagegenius/immich:v1.107.2-ig302. No cuda folder.

**Comment by martabal** [comment]
Can you run these 2 commands inside the Immich container and post the outputs?

`find /config -type f | wc -l`

`time lsiown -R abc:abc /config`

**Comment by Janczykkkko** [comment]
```shell
root@05cf99ba49f8:/# find /config -type f | wc -l
179
root@05cf99ba49f8:/# time lsiown -R abc:abc /config
real	0m0.015s
user	0m0.000s
sys	0m0.004s
```

**Comment by Janczykkkko** [comment]
Compose service:
```yaml
  immich:
    image: ghcr.io/imagegenius/immich:v1.108.0-ig303
    container_name: immich
    dns:
      - ${PIHOLE_ADDR}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=REDACTED
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich-redis
      - DISABLE_MACHINE_LEARNING=false
      - DISABLE_TYPESENSE=false
      - DB_PORT=5432
      - REDIS_PORT=6379
    volumes:
      - ${CONFIGS}/immich/config:/config
      - ${PHOTOS}/encoded-video:/photos/encoded-video
      - ${PHOTOS}/library:/photos/library
      - ${PHOTOS}/profile:/photos/profile
      - ${PHOTOS}/upload:/photos/upload
      - ${PHOTOS_THUMBNAILS}:/photos/thumbs
      - ${CONFIGS}/immich/ML:/config/machine-learning #optional
    expose:
      - 8080
    restart: always
    devices:
      - /dev/dri:/dev/dri
```
As I mentioned above, 1.107.1 booted up fine.
