### ISSUE TITLE
Permission issue out of the box

### ISSUE THREAD

**Issue by AliMickey** [imagegenius/docker-immich#416]
Hi,

There seems to be a permissions issue on the /photos mount when the container starts up, I create all folders using my user on the host but perms change to:

```
drwxr-xr-x  3 1000  100 4096 Jul 16 10:11 config
drwx------ 20  999  100 4096 Jul 16 10:11 db
-rw-r--r--  1 1000  100 1324 Jul 16 10:11 docker-compose.yml
drwxr-xr-x  2  911 1001 4096 Jul 16 10:10 photos
```

If I manually chown the photos folder, it will reset to the above 911/1001 permissions on container restart.

docker-compose.yml
```
services:

  immich:
    container_name: immich
    image: ghcr.io/imagegenius/immich:latest
    restart: unless-stopped
    networks:
      - apps
    expose:
      - 8080
    environment:
      - PGID=100
      - PUID=1000
      - TZ=Australia/Sydney
      - DB_HOSTNAME=immichDB
      - DB_DATABASE_NAME=immich
      - DB_USERNAME=immichUser
      - DB_PASSWORD=<password>
      - REDIS_HOSTNAME=immichRedis
    volumes:
      - ./config:/config
      - ./photos:/photos
      - /mnt/hdd/media/photos:/libraries:ro


  immichDB:
    container_name: immichDB
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    restart: unless-stopped
    networks:
      - apps
    expose:
      - 5432
    environment:
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichUser
      - POSTGRES_PASSWORD=
    volumes:
      - ./db:/var/lib/postgresql/data


  immichRedis:
    container_name: immichRedis
    image: redis:latest
    networks:
      - apps
    expose:
      - 6379


networks:
  apps:
    external: true
```
