### ISSUE TITLE
OpenVINO IGPU acceleration unavailable

### ISSUE THREAD

**Issue by haeho7** [imagegenius/docker-immich#497]
First, thank you for your excellent work on this container! 

I use docker compose in unRIAD to deploy the OpenVINO branch immich image. By adding the `/dev/dri` device, video transcoding can call IGPU acceleration normally, but machine learning OpenVINO cannot call acceleration.

## Environment

- **unRAID version:** 6.12.14
- **Linux kernel version:** 6.1.118
- **CPU:** Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
- **Immich version:** 1.124.2-openvino, 1.128.0-openvino (imagegenius/immich)

## Observed Behavior

Video transcoding successfully uses IGPU via /dev/dri passthrough, but machine learning falls back to CPU:

```log
[03/06/25 00:25:10] INFO     Loading textual model                              
                             'XLM-Roberta-Large-Vit-B-16Plus' to memory         
[03/06/25 00:25:10] DEBUG    Available ORT providers:                           
                             {'OpenVINOExecutionProvider',                      
                             'CPUExecutionProvider'}                            
[03/06/25 00:25:10] DEBUG    Available OpenVINO devices: ['CPU']                
[03/06/25 00:25:10] WARNING  No GPU device found in OpenVINO. Falling back to   
                             CPU.                                               
[03/06/25 00:25:10] INFO     Setting execution providers to                     
                             ['CPUExecutionProvider'], in descending order of   
                             preference                                         
```

[magegenius-immich-detail.log](https://github.com/user-attachments/files/19093730/magegenius-immich-detail.log)

Device visibility confirmed in container:

```sh
root@NAS:/mnt/user/appdata/immich# docker exec -it immich bash
root@NAS:/# ls -al /dev/dri/
total 0
drwxr-xr-x 2 root root            80 Mar  5 23:58 .
drwxr-xr-x 7 root root           380 Mar  5 23:58 ..
crwxrwxrwx 1 root video8z2c 226,   0 Mar  5 23:58 card0
crwxrwxrwx 1 root video8z2c 226, 128 Mar  5 23:58 renderD128
```

Use intel-gpu-top to check the usage:

```log
intel-gpu-top: Intel Coffeelake (Gen9) @ /dev/dri/card0 -  161/ 161 MHz;   0% RC6;  0.82/43.90 W;      312 irqs/s

      IMC reads:    11612 MiB/s
     IMC writes:     6507 MiB/s

         ENGINES     BUSY                                                                                                         MI_SEMA MI_WAIT
       Render/3D    7.13% |███████▎                                                                                             |      0%      0%
         Blitter    0.00% |                                                                                                     |      0%      0%
           Video    4.44% |████▌                                                                                                |      2%      0%
    VideoEnhance    0.00% |                                                                                                     |      0%      0%

  PID             Render/3D                         Blitter                           Video                        VideoEnhance            NAME  
27979 |██                             ||                               ||█▍                             ||                               | ffmpeg
```

## Configuration Attempt

<details><summary>docker-compose.yml (imagegenius/immich)</summary>

```yaml
services:
  immich:
    image: ghcr.io/imagegenius/immich:1.128.0-openvino
    container_name: immich
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - 'c 189:* rmw'
    environment:
      PUID: 99
      PGID: 100
      UMASK: 022
      TZ: Asia/Shanghai
      DB_HOSTNAME: <IP_ADDRESS>
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: <IP_ADDRESS>
      REDIS_PORT: 16379
      REDIS_PASSWORD:
      IMMICH_PORT: 8003
      MACHINE_LEARNING_HOST: 127.0.0.1
      MACHINE_LEARNING_PORT: 3003
      MACHINE_LEARNING_WORKERS: 1
      MACHINE_LEARNING_WORKER_TIMEOUT: 300
      IMMICH_LOG_LEVEL: debug
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./immich-data/config:/config
      - ./immich-data/data/photos:/photos
      - ./immich-data/data/libraries:/libraries

  immich-redis:
    image: redis
    container_name: immich-redis
    network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - 16379:6379

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich-postgres
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
```
</details>

## Successful Comparison

Using the [immich-app](https://github.com/immich-app/immich/tree/v1.128.0/docker) docker image for deployment in the same running environment, both video transcoding and machine learning can be accelerated by IGPU.

<details> <summary>Working docker-compose.yml (immich-app)</summary>

```yaml
services:
  immich-app-server:
    image: ghcr.io/immich-app/immich-server:v1.128.0
    container_name: immich-app-server
    #network_mode: bridge
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - immich-app-redis
      - immich-app-postgres
    environment:
      TZ: Asia/Shanghai
      IMMICH_ENV: production
      IMMICH_LOG_LEVEL: debug
      REDIS_HOSTNAME: immich-app-redis
      REDIS_PORT: 6379
      #REDIS_PASSWORD:
      DB_HOSTNAME: immich-app-postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
    volumes:
      - ./immich-data/library:/usr/src/app/upload
    ports:
      - 2283:2283

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.128.0-openvino
    container_name: immich-app-machine-learning
    #network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      IMMICH_LOG_LEVEL: debug
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./learning-data/model-cache:/cache

  immich-app-redis:
    image: docker.io/redis:6.2-alpine
    container_name: immich-app-redis
    #network_mode: bridge
    restart: unless-stopped

  immich-app-postgres:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich-app-postgres
    #network_mode: bridge
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
```
</details>

Working ML logs show GPU detection:

```log
immich-app-machine-learning  | [03/06/25 00:22:58] INFO     Loading textual model                              
immich-app-machine-learning  |                              'XLM-Roberta-Large-Vit-B-16Plus' to memory         
immich-app-machine-learning  | [03/06/25 00:22:58] DEBUG    Available ORT providers: {'CPUExecutionProvider',  
immich-app-machine-learning  |                              'OpenVINOExecutionProvider'}                       
immich-app-machine-learning  | [03/06/25 00:22:58] DEBUG    Available OpenVINO devices: ['CPU', 'GPU']         
immich-app-machine-learning  | [03/06/25 00:22:58] INFO     Setting execution providers to                     
immich-app-machine-learning  |                              ['OpenVINOExecutionProvider',                      
immich-app-machine-learning  |                              'CPUExecutionProvider'], in descending order of    
immich-app-machine-learning  |                              preference                                         
immich-app-machine-learning  | [03/06/25 00:22:58] DEBUG    Setting execution provider options to              
immich-app-machine-learning  |                              [{'device_type': 'GPU.0', 'precision': 'FP32',     
immich-app-machine-learning  |                              'cache_dir':                                       
immich-app-machine-learning  |                              '/cache/clip/XLM-Roberta-Large-Vit-B-16Plus/textual
immich-app-machine-learning  |                              /openvino'}, {'arena_extend_strategy':             
immich-app-machine-learning  |                              'kSameAsRequested'}]                               
immich-app-machine-learning  | [03/06/25 00:22:58] DEBUG    Setting execution_mode to ORT_SEQUENTIAL
```

[immich-app-detail.log](https://github.com/user-attachments/files/19093729/immich-app-detail.log)

Use intel-gpu-top to check the usage:

```log
intel-gpu-top: Intel Coffeelake (Gen9) @ /dev/dri/card0 - 1148/1149 MHz;   0% RC6; 12.16/55.02 W;      747 irqs/s

      IMC reads:    21858 MiB/s
     IMC writes:     3563 MiB/s

         ENGINES     BUSY                                                                                                         MI_SEMA MI_WAIT
       Render/3D   99.99% |█████████████████████████████████████████████████████████████████████████████████████████████████████|      0%      0%
         Blitter    0.00% |                                                                                                     |      0%      0%
           Video   15.86% |████████████████▏                                                                                    |      6%      0%
    VideoEnhance    0.00% |                                                                                                     |      0%      0%

  PID            Render/3D                        Blitter                          Video                        VideoEnhance           NAME      
28731 |██████████████████████████▊   ||                              ||                              ||                              | gunicorn  
18353 |███▋                          ||                              ||█████                         ||                              | ffmpeg    

```

Could we investigate why the container isn't detecting OpenVINO-capable GPUs despite successful device passthrough? I'm happy to provide additional testing or logs if needed.
