### ISSUE TITLE
Sample OpenVINO with docker compose

### ISSUE THREAD

**Issue by webysther** [imagegenius/docker-immich#504]
Looks like the `device_cgroup_rules` don't work anymore with the current version of docker compose (https://github.com/docker/compose/issues/8251) there a sample of how use OpenVINO with docker compose? I need to set the version 2.4? In the https://github.com/imagegenius/docker-immich?tab=readme-ov-file#intel-hardware-acceleration the sample is partial or a missed the location with the docker compose sample?

**Comment by martabal** [comment]
You just need to translate the docker run arguments to docker-compose. Something like this should work:

```yml
  immich:
    image: ghcr.io/imagegenius/immich:openvino
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_libraries:/libraries #optional
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:8080
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
```
