### ISSUE TITLE
Connection refused - Immich Server listening on http://127.0.0.1:8082

### ISSUE THREAD

**Issue by socram70** [imagegenius/docker-immich#555]
Hi.

I slightly modified your docker-compose as port 8080 is blocked for other purposes on my server. Everything is starting fine, the database gets set up, folders in the photos folder are created and the log looks fine, but my connection to my LAN-IP on port 8082 fails:

```
[...]
[Nest] 235  - 04/27/2025, 12:23:34 PM     LOG [Api:Bootstrap] Immich Server is listening on http://127.0.0.1:8082 [v1.132.1] [production] 

Connection to localhost (127.0.0.1) 8082 port [tcp/*] succeeded!

[ig-init] done.

Detected CPU Cores: 12

Starting microservices worker

[04/27/25 12:23:38] INFO     Starting gunicorn 23.0.0                           

[04/27/25 12:23:38] INFO     Listening at: http://0.0.0.0:3003 (285)            

[04/27/25 12:23:38] INFO     Using worker: immich_ml.config.CustomUvicornWorker 

[04/27/25 12:23:38] INFO     Booting worker with pid: 287                       

[...}
}
```

SERVER_HOST is set to 0.0.0.0 and SERVER_PORT is adapted to 8082 too (as well as the exposed ports):

```
services:
  immich:
    image: ghcr.io/imagegenius/immich:openvino
    container_name: immich
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri    
    environment:
      - PUID=1337 # my docker user
      - PGID=137 # my user group
      - TZ=Europe/Berlin
      - DB_HOSTNAME=192.168.25.55
      - DB_USERNAME=immich
      - DB_PASSWORD=MYPASSWORD
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.25.55
      - DB_PORT=5433 #optional
      - REDIS_PORT=6380 #optional
      - REDIS_PASSWORD= #optional
      - SERVER_HOST=0.0.0.0 #optional
      - SERVER_PORT=8082 #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /opt/docker/immich/config:/config
      - /media/bilder:/photos
      - /opt/docker/immich/libraries:/libraries #optional
    ports:
      - 8082:8080
    restart: unless-stopped

# This container requires an external application to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - 6380:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 5433:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: MYPASSWORD
      POSTGRES_DB: immich
      UID: 1337
      PGID: 137
    volumes:
      - /opt/docker/immich/postgres:/var/lib/postgresql/data
```

Maybe someone is seeing something here I'm completely missing?
