### ISSUE TITLE
Docker Secrets

### ISSUE THREAD

**Issue by stlouisn** [imagegenius/docker-immich#571]
Error: No PostgreSQL database password has been specified in the 'DB_PASSWORD' variable. 

Does not seem to detect the DB_PASSWORD env when using docker secrets as DB_PASSWORD_FILE.

compose.yaml :
```yaml
networks:

    default_immich:
        name: default_immich
        external: false

services:

    immich:
        image: ghcr.io/imagegenius/immich:latest
        container_name: immich
        hostname: immich
        labels:
            traefik.enable: false
        secrets:
            - postgres_immich_password
        env_file:
            - .env
            - .immich.env
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /docker/immich/config:/config
            - /docker/immich/pictures:/photos
            - /docker/immich/libraries:/libraries
        security_opt:
            - "no-new-privileges"
        healthcheck:
            disable: true
        networks:
            - frontend
            - default_immich
        depends_on:
            traefik: 
                condition: service_healthy
                restart: true
            immich-postgres:
                condition: service_healthy
                restart: true
            immich-redis:
                condition: service_healthy
                restart: true
        ports:
            - 8080:8080

    immich-postgres:
        image: ghcr.io/tensorchord/vchord-postgres:pg17-v0.4.1
        container_name: immich-postgres
        hostname: immich-postgres
        labels:
            traefik.enable: false
        secrets:
            - postgres_immich_password
        env_file:
            - .env
            - .pguser.env
            - .postgres.env
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /docker/immich/data:/var/lib/postgresql/data
        security_opt:
            - "no-new-privileges"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - default_immich

    immich-redis:
        image: docker.io/library/redis:latest
        container_name: immich-redis
        hostname: immich-redis
        labels:
            traefik.enable: false
        env_file:
            - .env
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
        security_opt:
            - "no-new-privileges"
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - default_immich
```

.immich.env :
```
PUID=1000
PGID=1000

DB_HOSTNAME="immich-postgres"
DB_USERNAME="immich"
DB_PASSWORD_FILE="/run/secrets/postgres_immich_password"
DB_DATABASE_NAME="immich"

REDIS_HOSTNAME=immich-redis
```
Any chance to implement this functionality?
