### ISSUE TITLE
Trafik Configs?

### ISSUE THREAD

**Issue by Chrisputer** [imagegenius/docker-immich#66]
More of a request than a problem. 
I cannot figure for the life of me how to get Traefik (which does all the http>https middleware stuff) to proxy to immich. Any help would be awesome. 
My Traefik service is a separate container all and not part of any other "Stack."

**Comment by martabal** [comment]
Traefik is not my main reverse proxy, but I played with it a few months ago and manged to manually route immich (note that my provider is a file) :
```yaml
http:
  routers:
    immich:
      entryPoints:
        - websecure
      rule: 'Host(`immich.example.com`)'
      service: immich

  services:
    immich:
      loadBalancer:
        servers:
          - url: http://immich:8080/
```
It is routed just like other services
