### ISSUE TITLE
AI tagging not working

### ISSUE THREAD

**Issue by Savanta** [imagegenius/docker-immich#95]
Log:
```
[Nest] 427  - 05/29/2023, 11:00:48 AM   ERROR [SmartInfoService] Unable run object detection pipeline: 131d4314-bd02-460b-bc5b-56f8b0217f28
Error: connect ECONNREFUSED 127.0.0.1:3003
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```
Docker compose:
```
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    mem_limit: 2GB
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - DB_HOSTNAME=ImmichDB
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=ImmichRedis
      - DISABLE_MACHINE_LEANRNING=false #optional
      - DISABLE_TYPESENSE=false #optional
    volumes:
      - /media/Dane/.docker/immich/config:/config
      - /media/Dane/Library/Photos:/photos
      - /media/Dane/.docker/immich/ai:/config/machine-learning
    restart: unless-stopped
    networks:
      - InternalNPM

  redis:
    image: redis
    container_name: ImmichRedis
    networks:
      - InternalNPM

  postgres14:
    image: postgres:14
    container_name: ImmichDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /media/Dane/.docker/immich/db:/var/lib/postgresql/data
    networks:
      - InternalNPM

networks:
  InternalNPM:
      external: true
```
[immich_logs](https://github.com/imagegenius/docker-immich/files/11590346/_immich_logs.1.txt)
